version: "3"

volumes:
  redis_data:
  postgres_data:

services:
  redis:
    image: redis:3.2
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lTSNXWCbqQ
      POSTGRES_USER: docgi
      POSTGRES_DB: docgi

  django:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=configs.settings.dev
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py migrate &&
             uwsgi --http :8000 \
                   --chdir /home/docgi/ \
                   -w configs.wsgi:application"
