version: "3"

volumes:
  redis_data:
  postgres_data:

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12.0-alpine
    ports:
      - 1234:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lTSNXWCbqQ
      POSTGRES_USER: docgi
      POSTGRES_DB: docgi
