# Generated by Django 3.2.3 on 2021-05-22 16:52

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import docgi.workspaces.models
import imagekit.models.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.SlugField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=docgi.workspaces.models.Workspace.logo_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Member')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member_sets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('activate', models.BooleanField(db_index=True, default=True)),
                ('workspace_role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Member')], default=2)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('workspace', 'user'), name='unique_workspace_user_constraint'),
        ),
        migrations.AlterIndexTogether(
            name='workspacemember',
            index_together={('workspace', 'user', 'is_removed')},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'workspace')},
        ),
    ]
