# Generated by Django 3.0.3 on 2020-03-02 19:08

import apps.utils.docgi_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_collection_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='color',
            field=apps.utils.docgi_models.ColorField(blank=True, default='cdd7d6', max_length=6, null=True),
        ),
    ]
