# Generated by Django 2.2.5 on 2019-09-25 18:21

import apps.users.models
import django.core.files.storage
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=256, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.users.models.User.avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.users.models.User.avatar_path),
        ),
    ]
