# Generated by Django 2.2.5 on 2019-11-04 02:55

import apps.users.models
import django.core.files.storage
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_thumbnail',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.users.models.User.avatar_path),
        ),
    ]
