# Generated by Django 2.2.5 on 2019-09-25 18:21

import apps.workspaces.models
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('logo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.workspaces.models.Workspace.logo_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
