# Generated by Django 2.2.5 on 2019-10-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20191007_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.SlugField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
