# Generated by Django 3.2.3 on 2021-05-22 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocgiActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.TextField()),
                ('target_id', models.CharField(max_length=150)),
                ('at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
