# Generated by Django 3.2.3 on 2021-05-22 16:52

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import docgi.base.models
import docgi.documents.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('private', models.BooleanField(default=False)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('color', docgi.base.models.ColorField(blank=True, default='cdd7d6', max_length=6, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('html_content', models.TextField(blank=True)),
                ('json_content', models.JSONField(blank=True, default=list, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=docgi.documents.models.DocumentImage.image_path)),
            ],
        ),
    ]
