# Generated by Django 3.0.3 on 2020-04-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200307_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='members',
        ),
    ]
