# Generated by Django 3.0.3 on 2020-05-17 10:27

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import docgi.documents.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20200331_1442'),
        ('documents', '0003_auto_20200515_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=docgi.documents.models.DocumentImage.image_path)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.Workspace')),
            ],
        ),
    ]
