# Generated by Django 3.0.6 on 2020-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200529_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
